### ISSUE TITLE
Non-Library Saves Page Does Not Refresh When Importing Or Deleting

### ISSUE THREAD

**Issue by TheOnlyPete** [EclipseEmu/beta-issues#1]
Replication Steps:

1), Go to Settings > Non-Library Saves
2), Click the ellipses on an existing save to bring up the 'import/export/delete' menu.
3), Import a save or delete a save.

Expected Behaviour:
Page should refresh to show the changes 

Actual Behaviour:
Page does not refresh so you have to go back to settings then back into Non-Library Saves to see if the file has been deleted or uploaded

**Comment by magnetardev** [comment]
Pushed a fix

**Comment by TheOnlyPete** [comment]
I've tested but still have the same behaviour currently.
